#!/usr/bin/env python3
from Adafruit_HTU21D.HTU21D import HTU21D
import json

result = {}
try: 
    h = HTU21D()
    result["temperature_c"] = h.read_temperature()
    result["humidity"] = h.read_humidity()
    result["temperature_f"] = (result["temperature_c"]*1.8) + 32
    result["error"] = False
except:
    result["temperature_c"] = 0.0
    result["humidity"] = 0.0
    result["temperature_f"] = (result["temperature_c"]*1.8) + 32
    result["error"] = True

print(json.dumps(result))

try:
    h.reset()
except:
    pass